sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

branches:
    only:
        - master

cache:
    apt: true
    pip: true


env:
    - DB_PASSWORD=''

install:
    - pip install -r requirements.txt

script:
    - nosetests --with-coverage --cover-inclusive --cover-package=. --cover-erase
    - coverage report --omit 'lib/*,tests/*' --show-missing
